CREATE TABLE users
(
  ID INTEGER PRIMARY KEY NOT NULL,
  USER_FIRST_NAME VARCHAR(255) DEFAULT 'NULL',
  USER_LOGIN VARCHAR(255) DEFAULT 'NULL',
  USER_ROLE  INTEGER REFERENCES KEY,
  USER_PASSWORD VARCHAR(255) DEFAULT 'NULL',
  USER_EMAIL VARCHAR(255) DEFAULT 'NULL'
)